#!/bin/sh
#
# This script builds the binary with the same libc as the target system.
#
# Otherwise, we may encounter errors like these:
#
# ./permfixer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./permfixer)
# ./permfixer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./permfixer)

set -e
DOCKER_BUILDKIT=1 docker build --output . .
